import type { Metadata } from "next";
import { Inter_Tight as FontSans } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { Scroll } from "./scroll";
import Link from "next/link";

const fontSans = FontSans({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "indrazm - Software Engineer and Generalist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script src="https://cloud.umami.is/script.js" data-website-id="0fcf646c-ba48-4827-9c14-a256cbb49367" defer />
      <body className={`${fontSans.className} antialiased xl:p-0 p-6 relative min-h-[97vh]`}>
        <div className="absolute z-10 bottom-10 left-10 space-y-2">
          <Link
            href="/"
            className="flex items-center gap-2 p-2 border bg-zinc-600/20 backdrop-blur-sm hover:border-orange-600 transition duration-100 border-zinc-900 w-fit rounded-lg cursor-pointer text-xs"
          >
            <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24">
              <g fill="none" stroke="currentColor" stroke-width="1.5">
                <path d="M2 12.204c0-2.289 0-3.433.52-4.381c.518-.949 1.467-1.537 3.364-2.715l2-1.241C9.889 2.622 10.892 2 12 2s2.11.622 4.116 1.867l2 1.241c1.897 1.178 2.846 1.766 3.365 2.715S22 9.915 22 12.203v1.522c0 3.9 0 5.851-1.172 7.063S17.771 22 14 22h-4c-3.771 0-5.657 0-6.828-1.212S2 17.626 2 13.725z"></path>
                <path stroke-linecap="round" d="M9 16c.85.63 1.885 1 3 1s2.15-.37 3-1"></path>
              </g>
            </svg>
            Home
          </Link>
          <Link
            href="/language-and-frameworks"
            className="block p-2 border bg-zinc-600/20 backdrop-blur-sm hover:border-orange-600 transition duration-100 border-zinc-900 w-fit rounded-lg cursor-pointer text-xs"
          >
            Language and Frameworks
          </Link>
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
